### ISSUE TITLE
no matching manifest for linux/arm64 in the manifest list entries

### ISSUE THREAD

**Issue by ShihChunHao** [Sinotrade/Shioaji#136]
I'm using iMac M1. (Apple Silicon Version)

When I use : docker pull sinotrade/shioaji
I found the error:
Using default tag: latest
latest: Pulling from sinotrade/shioaji
no matching manifest for linux/arm64 in the manifest list entries

**Comment by ypochien** [comment]
Thank you for reaching out with your issue. It appears that the problem you're encountering is due to the fact that the "shioaji"  is only compatible with the x86 platform, while your iMac M1 uses the ARM64 architecture.

To resolve this issue, you will need to install an x86 version of Python through Rosetta 2, which is a translation layer that allows you to run x86 applications on your Apple Silicon (M1) device.

Please follow [link](https://towardsdatascience.com/how-to-use-manage-multiple-python-versions-on-an-apple-silicon-m1-mac-d69ee6ed0250) to install the x86 version of Python using Rosetta 2:
